// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/modules/configure/entrance_factory.proto

#ifndef PROTOBUF_INCLUDED_src_2fmodules_2fconfigure_2fentrance_5ffactory_2eproto
#define PROTOBUF_INCLUDED_src_2fmodules_2fconfigure_2fentrance_5ffactory_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_src_2fmodules_2fconfigure_2fentrance_5ffactory_2eproto 

namespace protobuf_src_2fmodules_2fconfigure_2fentrance_5ffactory_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_src_2fmodules_2fconfigure_2fentrance_5ffactory_2eproto
namespace peleus {
namespace modules {
namespace configure {
class entrance_conf;
class entrance_confDefaultTypeInternal;
extern entrance_confDefaultTypeInternal _entrance_conf_default_instance_;
}  // namespace configure
}  // namespace modules
}  // namespace peleus
namespace google {
namespace protobuf {
template<> ::peleus::modules::configure::entrance_conf* Arena::CreateMaybeMessage<::peleus::modules::configure::entrance_conf>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace peleus {
namespace modules {
namespace configure {

// ===================================================================

class entrance_conf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:peleus.modules.configure.entrance_conf) */ {
 public:
  entrance_conf();
  virtual ~entrance_conf();

  entrance_conf(const entrance_conf& from);

  inline entrance_conf& operator=(const entrance_conf& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  entrance_conf(entrance_conf&& from) noexcept
    : entrance_conf() {
    *this = ::std::move(from);
  }

  inline entrance_conf& operator=(entrance_conf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const entrance_conf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const entrance_conf* internal_default_instance() {
    return reinterpret_cast<const entrance_conf*>(
               &_entrance_conf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(entrance_conf* other);
  friend void swap(entrance_conf& a, entrance_conf& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline entrance_conf* New() const final {
    return CreateMaybeMessage<entrance_conf>(NULL);
  }

  entrance_conf* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<entrance_conf>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const entrance_conf& from);
  void MergeFrom(const entrance_conf& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(entrance_conf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required string path = 2;
  bool has_path() const;
  void clear_path();
  static const int kPathFieldNumber = 2;
  const ::std::string& path() const;
  void set_path(const ::std::string& value);
  #if LANG_CXX11
  void set_path(::std::string&& value);
  #endif
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  ::std::string* mutable_path();
  ::std::string* release_path();
  void set_allocated_path(::std::string* path);

  // @@protoc_insertion_point(class_scope:peleus.modules.configure.entrance_conf)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_path();
  void clear_has_path();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr path_;
  friend struct ::protobuf_src_2fmodules_2fconfigure_2fentrance_5ffactory_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// entrance_conf

// required string name = 1;
inline bool entrance_conf::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void entrance_conf::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void entrance_conf::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void entrance_conf::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& entrance_conf::name() const {
  // @@protoc_insertion_point(field_get:peleus.modules.configure.entrance_conf.name)
  return name_.GetNoArena();
}
inline void entrance_conf::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:peleus.modules.configure.entrance_conf.name)
}
#if LANG_CXX11
inline void entrance_conf::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:peleus.modules.configure.entrance_conf.name)
}
#endif
inline void entrance_conf::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:peleus.modules.configure.entrance_conf.name)
}
inline void entrance_conf::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:peleus.modules.configure.entrance_conf.name)
}
inline ::std::string* entrance_conf::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:peleus.modules.configure.entrance_conf.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* entrance_conf::release_name() {
  // @@protoc_insertion_point(field_release:peleus.modules.configure.entrance_conf.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void entrance_conf::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:peleus.modules.configure.entrance_conf.name)
}

// required string path = 2;
inline bool entrance_conf::has_path() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void entrance_conf::set_has_path() {
  _has_bits_[0] |= 0x00000002u;
}
inline void entrance_conf::clear_has_path() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void entrance_conf::clear_path() {
  path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_path();
}
inline const ::std::string& entrance_conf::path() const {
  // @@protoc_insertion_point(field_get:peleus.modules.configure.entrance_conf.path)
  return path_.GetNoArena();
}
inline void entrance_conf::set_path(const ::std::string& value) {
  set_has_path();
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:peleus.modules.configure.entrance_conf.path)
}
#if LANG_CXX11
inline void entrance_conf::set_path(::std::string&& value) {
  set_has_path();
  path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:peleus.modules.configure.entrance_conf.path)
}
#endif
inline void entrance_conf::set_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_path();
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:peleus.modules.configure.entrance_conf.path)
}
inline void entrance_conf::set_path(const char* value, size_t size) {
  set_has_path();
  path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:peleus.modules.configure.entrance_conf.path)
}
inline ::std::string* entrance_conf::mutable_path() {
  set_has_path();
  // @@protoc_insertion_point(field_mutable:peleus.modules.configure.entrance_conf.path)
  return path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* entrance_conf::release_path() {
  // @@protoc_insertion_point(field_release:peleus.modules.configure.entrance_conf.path)
  if (!has_path()) {
    return NULL;
  }
  clear_has_path();
  return path_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void entrance_conf::set_allocated_path(::std::string* path) {
  if (path != NULL) {
    set_has_path();
  } else {
    clear_has_path();
  }
  path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), path);
  // @@protoc_insertion_point(field_set_allocated:peleus.modules.configure.entrance_conf.path)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace configure
}  // namespace modules
}  // namespace peleus

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_src_2fmodules_2fconfigure_2fentrance_5ffactory_2eproto
